remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
title: Quick Mapping Project
description: A JICA Co-creation, Innovation, and Circulation Initiative
github:
  is_project_page: false